export const operations = [
  ["vote_operation", "voter upvote @author/permalink, vote strength : 1000=1%"],
  ["comment_operation", "author replied to @parent_author/parent_permlink"],
  ["transfer_operation", "from transfer amount to 'user' memo "],
  ["transfer_to_vesting_operation", "from vest amount to 'user'"],
  [
    "withdraw_vesting_operation",
    "account withdraw verting_shares (convert to HP) from vesting (show details json)",
  ],
  [
    "limit_order_create_operation",
    "owner wants min_to_receive for amount_to_sell (show details json)",
  ],
  ["limit_order_cancel_operation", "owner caldel order orderid"],
  [
    "feed_publish_operation",
    "publisher feed price exchange_rate (base/quote ? ??? ?)",
  ],
  ["convert_operation", "owner conversion request : amount to HIVE"],
  [
    "account_create_operation",
    "creator create account new_account_name (show details json)",
  ],
  [
    "account_update_operation",
    "account update account data (show details json)",
  ],
  ["witness_update_operation", "owner update witness (show details json)"],
  ["account_witness_vote_operation", "account approve witness 'user'"],
  ["account_witness_proxy_operation", "account set proxy(user) as proxy"],
  ["pow_operation", "worker_account foud a pow"],
  ["custom_operation", "test"],
  ["report_over_production_operation", "test"],
  ["delete_comment_operation", "test"],
  ["custom_json_operation", "test"],
  ["comment_options_operation", "test"],
  ["set_withdraw_vesting_route_operation", "test"],
  ["limit_order_create2_operation", "test"],
  ["claim_account_operation", "test"],
  ["create_claimed_account_operation", "test"],
  ["request_account_recovery_operation", "test"],
  ["recover_account_operation", "test"],
  ["change_recovery_account_operation", "test"],
  ["escrow_transfer_operation", "test"],
  ["escrow_dispute_operation", "test"],
  ["escrow_release_operation", "test"],
  ["pow2_operation", "test"],
  ["pescrow_approve_operation", "test"],
  ["transfer_to_savings_operation", "test"],
  ["transfer_from_savings_operation", "test"],
  ["cancel_transfer_from_savings_operation", "test"],
  ["custom_binary_operation", "test"],
  ["decline_voting_rights_operation", "test"],
  ["reset_account_operation", "test"],
  ["set_reset_account_operation", "test"],
  ["claim_reward_balance_operation", "test"],
  ["delegate_vesting_shares_operation", "test"],
  ["account_create_with_delegation_operation", "test"],
  ["witness_set_properties_operation", "test"],
  ["account_update2_operation", "test"],
  ["create_proposal_operation", "test"],
  ["update_proposal_votes_operation", "test"],
  ["remove_proposal_operation", "test"],
  ["update_proposal_operation", "test"],
  ["collateralized_convert_operation", "test"],
  ["recurrent_transfer_operation", "test"],
  ["fill_convert_request_operation", "test"],
  ["author_reward_operation", "test"],
  ["curation_reward_operation", "test"],
  ["comment_reward_operation", "test"],
  ["liquidity_reward_operation", "test"],
  ["interest_operation", "test"],
  ["fill_vesting_withdraw_operation", "test"],
  ["fill_order_operation", "test"],
  ["shutdown_witness_operation", "test"],
  ["fill_transfer_from_savings_operation", "test"],
  ["hardfork_operation", "test"],
  ["comment_payout_update_operation", "test"],
  ["return_vesting_delegation_operation", "test"],
  ["comment_benefactor_reward_operation", "test"],
  ["producer_reward_operation", "test"],
  ["clear_null_account_balance_operation", "test"],
  ["proposal_pay_operation", "test"],
  ["sps_fund_operation", "test"],
  ["hardfork_hive_operation", "test"],
  ["hardfork_hive_restore_operation", "test"],
  ["delayed_voting_operation", "test"],
  ["consolidate_treasury_balance_operation", "test"],
  ["effective_comment_vote_operation", "test"],
  ["ineffective_delete_comment_operation", "test"],
  ["sps_convert_operation", "test"],
  ["expired_account_notification_operation", "test"],
  ["changed_recovery_account_operation", "test"],
  ["transfer_to_vesting_completed_operation", "test"],
  ["pow_reward_operation", "test"],
  ["vesting_shares_split_operation", "test"],
  ["account_created_operation", "test"],
  ["fill_collateralized_convert_request_operation", "test"],
  ["system_warning_operation", "test"],
  ["fill_recurrent_transfer_operation", "test"],
  ["failed_recurrent_transfer_operation", "test"],
  ["limit_order_cancelled_operation", "test"],
];
