include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: hive/haf
    ref: e765a5b61e2c8fa4357b739b6b7bab55ccb94eee # develop
    file: /scripts/ci-helpers/prepare_data_image_job.yml # implicitly pulls templates/base.gitlab-ci.yml from common-ci-configuration
  - project: hive/common-ci-configuration
    ref: 69a155cc9861188941a3f1a31db049ecc71e8de0
    file:
      - /templates/dynamic_tag_jobs.gitlab-ci.yml